// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: zenith.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Zenith_Check_FullMethodName              = "/zenith.v2.Zenith/Check"
	Zenith_BatchCheck_FullMethodName         = "/zenith.v2.Zenith/BatchCheck"
	Zenith_WriteTuples_FullMethodName        = "/zenith.v2.Zenith/WriteTuples"
	Zenith_CheckContentChange_FullMethodName = "/zenith.v2.Zenith/CheckContentChange"
	Zenith_ListSubjects_FullMethodName       = "/zenith.v2.Zenith/ListSubjects"
	Zenith_GetRequestOutcome_FullMethodName  = "/zenith.v2.Zenith/GetRequestOutcome"
	Zenith_GetClusterStatus_FullMethodName   = "/zenith.v2.Zenith/GetClusterStatus"
	Zenith_AddLearner_FullMethodName         = "/zenith.v2.Zenith/AddLearner"
	Zenith_ProposeJoint_FullMethodName       = "/zenith.v2.Zenith/ProposeJoint"
	Zenith_ProposeFinalize_FullMethodName    = "/zenith.v2.Zenith/ProposeFinalize"
)

// ZenithClient is the client API for Zenith service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ZenithClient interface {
	Check(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckResponse, error)
	BatchCheck(ctx context.Context, in *BatchCheckRequest, opts ...grpc.CallOption) (*BatchCheckResponse, error)
	WriteTuples(ctx context.Context, in *WriteTuplesRequest, opts ...grpc.CallOption) (*WriteTuplesResponse, error)
	CheckContentChange(ctx context.Context, in *CheckContentChangeRequest, opts ...grpc.CallOption) (*CheckContentChangeResponse, error)
	ListSubjects(ctx context.Context, in *ListSubjectsRequest, opts ...grpc.CallOption) (*ListSubjectsResponse, error)
	GetRequestOutcome(ctx context.Context, in *GetRequestOutcomeRequest, opts ...grpc.CallOption) (*GetRequestOutcomeResponse, error)
	GetClusterStatus(ctx context.Context, in *GetClusterStatusRequest, opts ...grpc.CallOption) (*GetClusterStatusResponse, error)
	AddLearner(ctx context.Context, in *AddLearnerRequest, opts ...grpc.CallOption) (*MembershipResponse, error)
	ProposeJoint(ctx context.Context, in *ProposeJointRequest, opts ...grpc.CallOption) (*MembershipResponse, error)
	ProposeFinalize(ctx context.Context, in *GetClusterStatusRequest, opts ...grpc.CallOption) (*MembershipResponse, error)
}

type zenithClient struct {
	cc grpc.ClientConnInterface
}

func NewZenithClient(cc grpc.ClientConnInterface) ZenithClient {
	return &zenithClient{cc}
}

func (c *zenithClient) Check(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckResponse)
	err := c.cc.Invoke(ctx, Zenith_Check_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zenithClient) BatchCheck(ctx context.Context, in *BatchCheckRequest, opts ...grpc.CallOption) (*BatchCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchCheckResponse)
	err := c.cc.Invoke(ctx, Zenith_BatchCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zenithClient) WriteTuples(ctx context.Context, in *WriteTuplesRequest, opts ...grpc.CallOption) (*WriteTuplesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteTuplesResponse)
	err := c.cc.Invoke(ctx, Zenith_WriteTuples_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zenithClient) CheckContentChange(ctx context.Context, in *CheckContentChangeRequest, opts ...grpc.CallOption) (*CheckContentChangeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckContentChangeResponse)
	err := c.cc.Invoke(ctx, Zenith_CheckContentChange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zenithClient) ListSubjects(ctx context.Context, in *ListSubjectsRequest, opts ...grpc.CallOption) (*ListSubjectsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSubjectsResponse)
	err := c.cc.Invoke(ctx, Zenith_ListSubjects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zenithClient) GetRequestOutcome(ctx context.Context, in *GetRequestOutcomeRequest, opts ...grpc.CallOption) (*GetRequestOutcomeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRequestOutcomeResponse)
	err := c.cc.Invoke(ctx, Zenith_GetRequestOutcome_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zenithClient) GetClusterStatus(ctx context.Context, in *GetClusterStatusRequest, opts ...grpc.CallOption) (*GetClusterStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetClusterStatusResponse)
	err := c.cc.Invoke(ctx, Zenith_GetClusterStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zenithClient) AddLearner(ctx context.Context, in *AddLearnerRequest, opts ...grpc.CallOption) (*MembershipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MembershipResponse)
	err := c.cc.Invoke(ctx, Zenith_AddLearner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zenithClient) ProposeJoint(ctx context.Context, in *ProposeJointRequest, opts ...grpc.CallOption) (*MembershipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MembershipResponse)
	err := c.cc.Invoke(ctx, Zenith_ProposeJoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zenithClient) ProposeFinalize(ctx context.Context, in *GetClusterStatusRequest, opts ...grpc.CallOption) (*MembershipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MembershipResponse)
	err := c.cc.Invoke(ctx, Zenith_ProposeFinalize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ZenithServer is the server API for Zenith service.
// All implementations must embed UnimplementedZenithServer
// for forward compatibility.
type ZenithServer interface {
	Check(context.Context, *CheckRequest) (*CheckResponse, error)
	BatchCheck(context.Context, *BatchCheckRequest) (*BatchCheckResponse, error)
	WriteTuples(context.Context, *WriteTuplesRequest) (*WriteTuplesResponse, error)
	CheckContentChange(context.Context, *CheckContentChangeRequest) (*CheckContentChangeResponse, error)
	ListSubjects(context.Context, *ListSubjectsRequest) (*ListSubjectsResponse, error)
	GetRequestOutcome(context.Context, *GetRequestOutcomeRequest) (*GetRequestOutcomeResponse, error)
	GetClusterStatus(context.Context, *GetClusterStatusRequest) (*GetClusterStatusResponse, error)
	AddLearner(context.Context, *AddLearnerRequest) (*MembershipResponse, error)
	ProposeJoint(context.Context, *ProposeJointRequest) (*MembershipResponse, error)
	ProposeFinalize(context.Context, *GetClusterStatusRequest) (*MembershipResponse, error)
	mustEmbedUnimplementedZenithServer()
}

// UnimplementedZenithServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedZenithServer struct{}

func (UnimplementedZenithServer) Check(context.Context, *CheckRequest) (*CheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Check not implemented")
}
func (UnimplementedZenithServer) BatchCheck(context.Context, *BatchCheckRequest) (*BatchCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchCheck not implemented")
}
func (UnimplementedZenithServer) WriteTuples(context.Context, *WriteTuplesRequest) (*WriteTuplesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WriteTuples not implemented")
}
func (UnimplementedZenithServer) CheckContentChange(context.Context, *CheckContentChangeRequest) (*CheckContentChangeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckContentChange not implemented")
}
func (UnimplementedZenithServer) ListSubjects(context.Context, *ListSubjectsRequest) (*ListSubjectsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSubjects not implemented")
}
func (UnimplementedZenithServer) GetRequestOutcome(context.Context, *GetRequestOutcomeRequest) (*GetRequestOutcomeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRequestOutcome not implemented")
}
func (UnimplementedZenithServer) GetClusterStatus(context.Context, *GetClusterStatusRequest) (*GetClusterStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClusterStatus not implemented")
}
func (UnimplementedZenithServer) AddLearner(context.Context, *AddLearnerRequest) (*MembershipResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddLearner not implemented")
}
func (UnimplementedZenithServer) ProposeJoint(context.Context, *ProposeJointRequest) (*MembershipResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProposeJoint not implemented")
}
func (UnimplementedZenithServer) ProposeFinalize(context.Context, *GetClusterStatusRequest) (*MembershipResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProposeFinalize not implemented")
}
func (UnimplementedZenithServer) mustEmbedUnimplementedZenithServer() {}
func (UnimplementedZenithServer) testEmbeddedByValue()                {}

// UnsafeZenithServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ZenithServer will
// result in compilation errors.
type UnsafeZenithServer interface {
	mustEmbedUnimplementedZenithServer()
}

func RegisterZenithServer(s grpc.ServiceRegistrar, srv ZenithServer) {
	// If the following call pancis, it indicates UnimplementedZenithServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Zenith_ServiceDesc, srv)
}

func _Zenith_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZenithServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Zenith_Check_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZenithServer).Check(ctx, req.(*CheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Zenith_BatchCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZenithServer).BatchCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Zenith_BatchCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZenithServer).BatchCheck(ctx, req.(*BatchCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Zenith_WriteTuples_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteTuplesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZenithServer).WriteTuples(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Zenith_WriteTuples_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZenithServer).WriteTuples(ctx, req.(*WriteTuplesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Zenith_CheckContentChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckContentChangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZenithServer).CheckContentChange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Zenith_CheckContentChange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZenithServer).CheckContentChange(ctx, req.(*CheckContentChangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Zenith_ListSubjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSubjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZenithServer).ListSubjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Zenith_ListSubjects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZenithServer).ListSubjects(ctx, req.(*ListSubjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Zenith_GetRequestOutcome_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequestOutcomeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZenithServer).GetRequestOutcome(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Zenith_GetRequestOutcome_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZenithServer).GetRequestOutcome(ctx, req.(*GetRequestOutcomeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Zenith_GetClusterStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClusterStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZenithServer).GetClusterStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Zenith_GetClusterStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZenithServer).GetClusterStatus(ctx, req.(*GetClusterStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Zenith_AddLearner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddLearnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZenithServer).AddLearner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Zenith_AddLearner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZenithServer).AddLearner(ctx, req.(*AddLearnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Zenith_ProposeJoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProposeJointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZenithServer).ProposeJoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Zenith_ProposeJoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZenithServer).ProposeJoint(ctx, req.(*ProposeJointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Zenith_ProposeFinalize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClusterStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZenithServer).ProposeFinalize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Zenith_ProposeFinalize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZenithServer).ProposeFinalize(ctx, req.(*GetClusterStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Zenith_ServiceDesc is the grpc.ServiceDesc for Zenith service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Zenith_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "zenith.v2.Zenith",
	HandlerType: (*ZenithServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Check",
			Handler:    _Zenith_Check_Handler,
		},
		{
			MethodName: "BatchCheck",
			Handler:    _Zenith_BatchCheck_Handler,
		},
		{
			MethodName: "WriteTuples",
			Handler:    _Zenith_WriteTuples_Handler,
		},
		{
			MethodName: "CheckContentChange",
			Handler:    _Zenith_CheckContentChange_Handler,
		},
		{
			MethodName: "ListSubjects",
			Handler:    _Zenith_ListSubjects_Handler,
		},
		{
			MethodName: "GetRequestOutcome",
			Handler:    _Zenith_GetRequestOutcome_Handler,
		},
		{
			MethodName: "GetClusterStatus",
			Handler:    _Zenith_GetClusterStatus_Handler,
		},
		{
			MethodName: "AddLearner",
			Handler:    _Zenith_AddLearner_Handler,
		},
		{
			MethodName: "ProposeJoint",
			Handler:    _Zenith_ProposeJoint_Handler,
		},
		{
			MethodName: "ProposeFinalize",
			Handler:    _Zenith_ProposeFinalize_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "zenith.proto",
}
