// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: zenith.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Consistency struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Mode:
	//
	//	*Consistency_FullyConsistent
	//	*Consistency_AtLeastAsFresh
	//	*Consistency_AtExactRevision
	Mode          isConsistency_Mode `protobuf_oneof:"mode"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Consistency) Reset() {
	*x = Consistency{}
	mi := &file_zenith_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Consistency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Consistency) ProtoMessage() {}

func (x *Consistency) ProtoReflect() protoreflect.Message {
	mi := &file_zenith_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Consistency.ProtoReflect.Descriptor instead.
func (*Consistency) Descriptor() ([]byte, []int) {
	return file_zenith_proto_rawDescGZIP(), []int{0}
}

func (x *Consistency) GetMode() isConsistency_Mode {
	if x != nil {
		return x.Mode
	}
	return nil
}

func (x *Consistency) GetFullyConsistent() bool {
	if x != nil {
		if x, ok := x.Mode.(*Consistency_FullyConsistent); ok {
			return x.FullyConsistent
		}
	}
	return false
}

func (x *Consistency) GetAtLeastAsFresh() string {
	if x != nil {
		if x, ok := x.Mode.(*Consistency_AtLeastAsFresh); ok {
			return x.AtLeastAsFresh
		}
	}
	return ""
}

func (x *Consistency) GetAtExactRevision() string {
	if x != nil {
		if x, ok := x.Mode.(*Consistency_AtExactRevision); ok {
			return x.AtExactRevision
		}
	}
	return ""
}

type isConsistency_Mode interface {
	isConsistency_Mode()
}

type Consistency_FullyConsistent struct {
	FullyConsistent bool `protobuf:"varint,1,opt,name=fully_consistent,json=fullyConsistent,proto3,oneof"`
}

type Consistency_AtLeastAsFresh struct {
	AtLeastAsFresh string `protobuf:"bytes,2,opt,name=at_least_as_fresh,json=atLeastAsFresh,proto3,oneof"`
}

type Consistency_AtExactRevision struct {
	AtExactRevision string `protobuf:"bytes,3,opt,name=at_exact_revision,json=atExactRevision,proto3,oneof"`
}

func (*Consistency_FullyConsistent) isConsistency_Mode() {}

func (*Consistency_AtLeastAsFresh) isConsistency_Mode() {}

func (*Consistency_AtExactRevision) isConsistency_Mode() {}

type Tuple struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ObjectNamespace  string                 `protobuf:"bytes,1,opt,name=object_namespace,json=objectNamespace,proto3" json:"object_namespace,omitempty"`
	ObjectId         string                 `protobuf:"bytes,2,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	Relation         string                 `protobuf:"bytes,3,opt,name=relation,proto3" json:"relation,omitempty"`
	SubjectNamespace string                 `protobuf:"bytes,4,opt,name=subject_namespace,json=subjectNamespace,proto3" json:"subject_namespace,omitempty"`
	SubjectId        string                 `protobuf:"bytes,5,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	SubjectRelation  string                 `protobuf:"bytes,6,opt,name=subject_relation,json=subjectRelation,proto3" json:"subject_relation,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Tuple) Reset() {
	*x = Tuple{}
	mi := &file_zenith_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tuple) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tuple) ProtoMessage() {}

func (x *Tuple) ProtoReflect() protoreflect.Message {
	mi := &file_zenith_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tuple.ProtoReflect.Descriptor instead.
func (*Tuple) Descriptor() ([]byte, []int) {
	return file_zenith_proto_rawDescGZIP(), []int{1}
}

func (x *Tuple) GetObjectNamespace() string {
	if x != nil {
		return x.ObjectNamespace
	}
	return ""
}

func (x *Tuple) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *Tuple) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *Tuple) GetSubjectNamespace() string {
	if x != nil {
		return x.SubjectNamespace
	}
	return ""
}

func (x *Tuple) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *Tuple) GetSubjectRelation() string {
	if x != nil {
		return x.SubjectRelation
	}
	return ""
}

type CheckRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Store            string                 `protobuf:"bytes,1,opt,name=store,proto3" json:"store,omitempty"`
	ObjectNamespace  string                 `protobuf:"bytes,2,opt,name=object_namespace,json=objectNamespace,proto3" json:"object_namespace,omitempty"`
	ObjectId         string                 `protobuf:"bytes,3,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	Relation         string                 `protobuf:"bytes,4,opt,name=relation,proto3" json:"relation,omitempty"`
	SubjectNamespace string                 `protobuf:"bytes,5,opt,name=subject_namespace,json=subjectNamespace,proto3" json:"subject_namespace,omitempty"`
	SubjectId        string                 `protobuf:"bytes,6,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	Consistency      *Consistency           `protobuf:"bytes,7,opt,name=consistency,proto3" json:"consistency,omitempty"`
	RequiredToken    string                 `protobuf:"bytes,8,opt,name=required_token,json=requiredToken,proto3" json:"required_token,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CheckRequest) Reset() {
	*x = CheckRequest{}
	mi := &file_zenith_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRequest) ProtoMessage() {}

func (x *CheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zenith_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRequest.ProtoReflect.Descriptor instead.
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return file_zenith_proto_rawDescGZIP(), []int{2}
}

func (x *CheckRequest) GetStore() string {
	if x != nil {
		return x.Store
	}
	return ""
}

func (x *CheckRequest) GetObjectNamespace() string {
	if x != nil {
		return x.ObjectNamespace
	}
	return ""
}

func (x *CheckRequest) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *CheckRequest) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *CheckRequest) GetSubjectNamespace() string {
	if x != nil {
		return x.SubjectNamespace
	}
	return ""
}

func (x *CheckRequest) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *CheckRequest) GetConsistency() *Consistency {
	if x != nil {
		return x.Consistency
	}
	return nil
}

func (x *CheckRequest) GetRequiredToken() string {
	if x != nil {
		return x.RequiredToken
	}
	return ""
}

type CheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckResponse) Reset() {
	*x = CheckResponse{}
	mi := &file_zenith_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResponse) ProtoMessage() {}

func (x *CheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zenith_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResponse.ProtoReflect.Descriptor instead.
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return file_zenith_proto_rawDescGZIP(), []int{3}
}

func (x *CheckResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *CheckResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CheckResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type BatchCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Store         string                 `protobuf:"bytes,1,opt,name=store,proto3" json:"store,omitempty"`
	Consistency   *Consistency           `protobuf:"bytes,2,opt,name=consistency,proto3" json:"consistency,omitempty"`
	Items         []*CheckRequest        `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCheckRequest) Reset() {
	*x = BatchCheckRequest{}
	mi := &file_zenith_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCheckRequest) ProtoMessage() {}

func (x *BatchCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zenith_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCheckRequest.ProtoReflect.Descriptor instead.
func (*BatchCheckRequest) Descriptor() ([]byte, []int) {
	return file_zenith_proto_rawDescGZIP(), []int{4}
}

func (x *BatchCheckRequest) GetStore() string {
	if x != nil {
		return x.Store
	}
	return ""
}

func (x *BatchCheckRequest) GetConsistency() *Consistency {
	if x != nil {
		return x.Consistency
	}
	return nil
}

func (x *BatchCheckRequest) GetItems() []*CheckRequest {
	if x != nil {
		return x.Items
	}
	return nil
}

type BatchCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revision      uint64                 `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Results       []*CheckResponse       `protobuf:"bytes,3,rep,name=results,proto3" json:"results,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCheckResponse) Reset() {
	*x = BatchCheckResponse{}
	mi := &file_zenith_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCheckResponse) ProtoMessage() {}

func (x *BatchCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zenith_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCheckResponse.ProtoReflect.Descriptor instead.
func (*BatchCheckResponse) Descriptor() ([]byte, []int) {
	return file_zenith_proto_rawDescGZIP(), []int{5}
}

func (x *BatchCheckResponse) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *BatchCheckResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *BatchCheckResponse) GetResults() []*CheckResponse {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *BatchCheckResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type WriteTuplesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Store         string                 `protobuf:"bytes,1,opt,name=store,proto3" json:"store,omitempty"`
	Session       string                 `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
	Seq           uint64                 `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	Tuples        []*Tuple               `protobuf:"bytes,4,rep,name=tuples,proto3" json:"tuples,omitempty"`
	Deletes       []*Tuple               `protobuf:"bytes,5,rep,name=deletes,proto3" json:"deletes,omitempty"`
	RequestId     string                 `protobuf:"bytes,6,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteTuplesRequest) Reset() {
	*x = WriteTuplesRequest{}
	mi := &file_zenith_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteTuplesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteTuplesRequest) ProtoMessage() {}

func (x *WriteTuplesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zenith_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteTuplesRequest.ProtoReflect.Descriptor instead.
func (*WriteTuplesRequest) Descriptor() ([]byte, []int) {
	return file_zenith_proto_rawDescGZIP(), []int{6}
}

func (x *WriteTuplesRequest) GetStore() string {
	if x != nil {
		return x.Store
	}
	return ""
}

func (x *WriteTuplesRequest) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

func (x *WriteTuplesRequest) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *WriteTuplesRequest) GetTuples() []*Tuple {
	if x != nil {
		return x.Tuples
	}
	return nil
}

func (x *WriteTuplesRequest) GetDeletes() []*Tuple {
	if x != nil {
		return x.Deletes
	}
	return nil
}

func (x *WriteTuplesRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type WriteTuplesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Revision      uint64                 `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteTuplesResponse) Reset() {
	*x = WriteTuplesResponse{}
	mi := &file_zenith_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteTuplesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteTuplesResponse) ProtoMessage() {}

func (x *WriteTuplesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zenith_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteTuplesResponse.ProtoReflect.Descriptor instead.
func (*WriteTuplesResponse) Descriptor() ([]byte, []int) {
	return file_zenith_proto_rawDescGZIP(), []int{7}
}

func (x *WriteTuplesResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *WriteTuplesResponse) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *WriteTuplesResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CheckContentChangeRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Store            string                 `protobuf:"bytes,1,opt,name=store,proto3" json:"store,omitempty"`
	ObjectNamespace  string                 `protobuf:"bytes,2,opt,name=object_namespace,json=objectNamespace,proto3" json:"object_namespace,omitempty"`
	ObjectId         string                 `protobuf:"bytes,3,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	Relation         string                 `protobuf:"bytes,4,opt,name=relation,proto3" json:"relation,omitempty"`
	SubjectNamespace string                 `protobuf:"bytes,5,opt,name=subject_namespace,json=subjectNamespace,proto3" json:"subject_namespace,omitempty"`
	SubjectId        string                 `protobuf:"bytes,6,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	RequestId        string                 `protobuf:"bytes,7,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CheckContentChangeRequest) Reset() {
	*x = CheckContentChangeRequest{}
	mi := &file_zenith_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckContentChangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckContentChangeRequest) ProtoMessage() {}

func (x *CheckContentChangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zenith_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckContentChangeRequest.ProtoReflect.Descriptor instead.
func (*CheckContentChangeRequest) Descriptor() ([]byte, []int) {
	return file_zenith_proto_rawDescGZIP(), []int{8}
}

func (x *CheckContentChangeRequest) GetStore() string {
	if x != nil {
		return x.Store
	}
	return ""
}

func (x *CheckContentChangeRequest) GetObjectNamespace() string {
	if x != nil {
		return x.ObjectNamespace
	}
	return ""
}

func (x *CheckContentChangeRequest) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *CheckContentChangeRequest) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *CheckContentChangeRequest) GetSubjectNamespace() string {
	if x != nil {
		return x.SubjectNamespace
	}
	return ""
}

func (x *CheckContentChangeRequest) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *CheckContentChangeRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type CheckContentChangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Revision      uint64                 `protobuf:"varint,3,opt,name=revision,proto3" json:"revision,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckContentChangeResponse) Reset() {
	*x = CheckContentChangeResponse{}
	mi := &file_zenith_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckContentChangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckContentChangeResponse) ProtoMessage() {}

func (x *CheckContentChangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zenith_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckContentChangeResponse.ProtoReflect.Descriptor instead.
func (*CheckContentChangeResponse) Descriptor() ([]byte, []int) {
	return file_zenith_proto_rawDescGZIP(), []int{9}
}

func (x *CheckContentChangeResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *CheckContentChangeResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CheckContentChangeResponse) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *CheckContentChangeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ListSubjectsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Store           string                 `protobuf:"bytes,1,opt,name=store,proto3" json:"store,omitempty"`
	ObjectNamespace string                 `protobuf:"bytes,2,opt,name=object_namespace,json=objectNamespace,proto3" json:"object_namespace,omitempty"`
	ObjectId        string                 `protobuf:"bytes,3,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	Relation        string                 `protobuf:"bytes,4,opt,name=relation,proto3" json:"relation,omitempty"`
	Consistency     *Consistency           `protobuf:"bytes,5,opt,name=consistency,proto3" json:"consistency,omitempty"`
	Limit           uint32                 `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"` // 0 = default bound
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListSubjectsRequest) Reset() {
	*x = ListSubjectsRequest{}
	mi := &file_zenith_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSubjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSubjectsRequest) ProtoMessage() {}

func (x *ListSubjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zenith_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSubjectsRequest.ProtoReflect.Descriptor instead.
func (*ListSubjectsRequest) Descriptor() ([]byte, []int) {
	return file_zenith_proto_rawDescGZIP(), []int{10}
}

func (x *ListSubjectsRequest) GetStore() string {
	if x != nil {
		return x.Store
	}
	return ""
}

func (x *ListSubjectsRequest) GetObjectNamespace() string {
	if x != nil {
		return x.ObjectNamespace
	}
	return ""
}

func (x *ListSubjectsRequest) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *ListSubjectsRequest) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *ListSubjectsRequest) GetConsistency() *Consistency {
	if x != nil {
		return x.Consistency
	}
	return nil
}

func (x *ListSubjectsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type Subject struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SubjectNamespace string                 `protobuf:"bytes,1,opt,name=subject_namespace,json=subjectNamespace,proto3" json:"subject_namespace,omitempty"`
	SubjectId        string                 `protobuf:"bytes,2,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	SubjectRelation  string                 `protobuf:"bytes,3,opt,name=subject_relation,json=subjectRelation,proto3" json:"subject_relation,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Subject) Reset() {
	*x = Subject{}
	mi := &file_zenith_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subject) ProtoMessage() {}

func (x *Subject) ProtoReflect() protoreflect.Message {
	mi := &file_zenith_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subject.ProtoReflect.Descriptor instead.
func (*Subject) Descriptor() ([]byte, []int) {
	return file_zenith_proto_rawDescGZIP(), []int{11}
}

func (x *Subject) GetSubjectNamespace() string {
	if x != nil {
		return x.SubjectNamespace
	}
	return ""
}

func (x *Subject) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *Subject) GetSubjectRelation() string {
	if x != nil {
		return x.SubjectRelation
	}
	return ""
}

type ListSubjectsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subjects      []*Subject             `protobuf:"bytes,1,rep,name=subjects,proto3" json:"subjects,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Revision      uint64                 `protobuf:"varint,3,opt,name=revision,proto3" json:"revision,omitempty"`
	Complete      bool                   `protobuf:"varint,4,opt,name=complete,proto3" json:"complete,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSubjectsResponse) Reset() {
	*x = ListSubjectsResponse{}
	mi := &file_zenith_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSubjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSubjectsResponse) ProtoMessage() {}

func (x *ListSubjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zenith_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSubjectsResponse.ProtoReflect.Descriptor instead.
func (*ListSubjectsResponse) Descriptor() ([]byte, []int) {
	return file_zenith_proto_rawDescGZIP(), []int{12}
}

func (x *ListSubjectsResponse) GetSubjects() []*Subject {
	if x != nil {
		return x.Subjects
	}
	return nil
}

func (x *ListSubjectsResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ListSubjectsResponse) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *ListSubjectsResponse) GetComplete() bool {
	if x != nil {
		return x.Complete
	}
	return false
}

func (x *ListSubjectsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetRequestOutcomeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       string                 `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Seq           uint64                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	RequestId     string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequestOutcomeRequest) Reset() {
	*x = GetRequestOutcomeRequest{}
	mi := &file_zenith_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequestOutcomeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequestOutcomeRequest) ProtoMessage() {}

func (x *GetRequestOutcomeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zenith_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequestOutcomeRequest.ProtoReflect.Descriptor instead.
func (*GetRequestOutcomeRequest) Descriptor() ([]byte, []int) {
	return file_zenith_proto_rawDescGZIP(), []int{13}
}

func (x *GetRequestOutcomeRequest) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

func (x *GetRequestOutcomeRequest) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *GetRequestOutcomeRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type GetRequestOutcomeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Revision      uint64                 `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"`
	Result        string                 `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequestOutcomeResponse) Reset() {
	*x = GetRequestOutcomeResponse{}
	mi := &file_zenith_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequestOutcomeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequestOutcomeResponse) ProtoMessage() {}

func (x *GetRequestOutcomeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zenith_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequestOutcomeResponse.ProtoReflect.Descriptor instead.
func (*GetRequestOutcomeResponse) Descriptor() ([]byte, []int) {
	return file_zenith_proto_rawDescGZIP(), []int{14}
}

func (x *GetRequestOutcomeResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetRequestOutcomeResponse) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *GetRequestOutcomeResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *GetRequestOutcomeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetClusterStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClusterStatusRequest) Reset() {
	*x = GetClusterStatusRequest{}
	mi := &file_zenith_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClusterStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClusterStatusRequest) ProtoMessage() {}

func (x *GetClusterStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zenith_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClusterStatusRequest.ProtoReflect.Descriptor instead.
func (*GetClusterStatusRequest) Descriptor() ([]byte, []int) {
	return file_zenith_proto_rawDescGZIP(), []int{15}
}

type GetClusterStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Term          uint64                 `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	CommitIndex   uint64                 `protobuf:"varint,3,opt,name=commit_index,json=commitIndex,proto3" json:"commit_index,omitempty"`
	AppliedIndex  uint64                 `protobuf:"varint,4,opt,name=applied_index,json=appliedIndex,proto3" json:"applied_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClusterStatusResponse) Reset() {
	*x = GetClusterStatusResponse{}
	mi := &file_zenith_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClusterStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClusterStatusResponse) ProtoMessage() {}

func (x *GetClusterStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zenith_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClusterStatusResponse.ProtoReflect.Descriptor instead.
func (*GetClusterStatusResponse) Descriptor() ([]byte, []int) {
	return file_zenith_proto_rawDescGZIP(), []int{16}
}

func (x *GetClusterStatusResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *GetClusterStatusResponse) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *GetClusterStatusResponse) GetCommitIndex() uint64 {
	if x != nil {
		return x.CommitIndex
	}
	return 0
}

func (x *GetClusterStatusResponse) GetAppliedIndex() uint64 {
	if x != nil {
		return x.AppliedIndex
	}
	return 0
}

type AddLearnerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        uint64                 `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddLearnerRequest) Reset() {
	*x = AddLearnerRequest{}
	mi := &file_zenith_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddLearnerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddLearnerRequest) ProtoMessage() {}

func (x *AddLearnerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zenith_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddLearnerRequest.ProtoReflect.Descriptor instead.
func (*AddLearnerRequest) Descriptor() ([]byte, []int) {
	return file_zenith_proto_rawDescGZIP(), []int{17}
}

func (x *AddLearnerRequest) GetNodeId() uint64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

type ProposeJointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Voters        []uint64               `protobuf:"varint,1,rep,packed,name=voters,proto3" json:"voters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProposeJointRequest) Reset() {
	*x = ProposeJointRequest{}
	mi := &file_zenith_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProposeJointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposeJointRequest) ProtoMessage() {}

func (x *ProposeJointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zenith_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposeJointRequest.ProtoReflect.Descriptor instead.
func (*ProposeJointRequest) Descriptor() ([]byte, []int) {
	return file_zenith_proto_rawDescGZIP(), []int{18}
}

func (x *ProposeJointRequest) GetVoters() []uint64 {
	if x != nil {
		return x.Voters
	}
	return nil
}

type MembershipResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MembershipResponse) Reset() {
	*x = MembershipResponse{}
	mi := &file_zenith_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MembershipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MembershipResponse) ProtoMessage() {}

func (x *MembershipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zenith_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MembershipResponse.ProtoReflect.Descriptor instead.
func (*MembershipResponse) Descriptor() ([]byte, []int) {
	return file_zenith_proto_rawDescGZIP(), []int{19}
}

func (x *MembershipResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *MembershipResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_zenith_proto protoreflect.FileDescriptor

const file_zenith_proto_rawDesc = "" +
	"\n" +
	"\fzenith.proto\x12\tzenith.v2\"\x9d\x01\n" +
	"\vConsistency\x12+\n" +
	"\x10fully_consistent\x18\x01 \x01(\bH\x00R\x0ffullyConsistent\x12+\n" +
	"\x11at_least_as_fresh\x18\x02 \x01(\tH\x00R\x0eatLeastAsFresh\x12,\n" +
	"\x11at_exact_revision\x18\x03 \x01(\tH\x00R\x0fatExactRevisionB\x06\n" +
	"\x04mode\"\xe2\x01\n" +
	"\x05Tuple\x12)\n" +
	"\x10object_namespace\x18\x01 \x01(\tR\x0fobjectNamespace\x12\x1b\n" +
	"\tobject_id\x18\x02 \x01(\tR\bobjectId\x12\x1a\n" +
	"\brelation\x18\x03 \x01(\tR\brelation\x12+\n" +
	"\x11subject_namespace\x18\x04 \x01(\tR\x10subjectNamespace\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x05 \x01(\tR\tsubjectId\x12)\n" +
	"\x10subject_relation\x18\x06 \x01(\tR\x0fsubjectRelation\"\xb5\x02\n" +
	"\fCheckRequest\x12\x14\n" +
	"\x05store\x18\x01 \x01(\tR\x05store\x12)\n" +
	"\x10object_namespace\x18\x02 \x01(\tR\x0fobjectNamespace\x12\x1b\n" +
	"\tobject_id\x18\x03 \x01(\tR\bobjectId\x12\x1a\n" +
	"\brelation\x18\x04 \x01(\tR\brelation\x12+\n" +
	"\x11subject_namespace\x18\x05 \x01(\tR\x10subjectNamespace\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x06 \x01(\tR\tsubjectId\x128\n" +
	"\vconsistency\x18\a \x01(\v2\x16.zenith.v2.ConsistencyR\vconsistency\x12%\n" +
	"\x0erequired_token\x18\b \x01(\tR\rrequiredToken\"U\n" +
	"\rCheckResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x92\x01\n" +
	"\x11BatchCheckRequest\x12\x14\n" +
	"\x05store\x18\x01 \x01(\tR\x05store\x128\n" +
	"\vconsistency\x18\x02 \x01(\v2\x16.zenith.v2.ConsistencyR\vconsistency\x12-\n" +
	"\x05items\x18\x03 \x03(\v2\x17.zenith.v2.CheckRequestR\x05items\"\x90\x01\n" +
	"\x12BatchCheckResponse\x12\x1a\n" +
	"\brevision\x18\x01 \x01(\x04R\brevision\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x122\n" +
	"\aresults\x18\x03 \x03(\v2\x18.zenith.v2.CheckResponseR\aresults\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\xcb\x01\n" +
	"\x12WriteTuplesRequest\x12\x14\n" +
	"\x05store\x18\x01 \x01(\tR\x05store\x12\x18\n" +
	"\asession\x18\x02 \x01(\tR\asession\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x04R\x03seq\x12(\n" +
	"\x06tuples\x18\x04 \x03(\v2\x10.zenith.v2.TupleR\x06tuples\x12*\n" +
	"\adeletes\x18\x05 \x03(\v2\x10.zenith.v2.TupleR\adeletes\x12\x1d\n" +
	"\n" +
	"request_id\x18\x06 \x01(\tR\trequestId\"]\n" +
	"\x13WriteTuplesResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\x04R\brevision\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x80\x02\n" +
	"\x19CheckContentChangeRequest\x12\x14\n" +
	"\x05store\x18\x01 \x01(\tR\x05store\x12)\n" +
	"\x10object_namespace\x18\x02 \x01(\tR\x0fobjectNamespace\x12\x1b\n" +
	"\tobject_id\x18\x03 \x01(\tR\bobjectId\x12\x1a\n" +
	"\brelation\x18\x04 \x01(\tR\brelation\x12+\n" +
	"\x11subject_namespace\x18\x05 \x01(\tR\x10subjectNamespace\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x06 \x01(\tR\tsubjectId\x12\x1d\n" +
	"\n" +
	"request_id\x18\a \x01(\tR\trequestId\"~\n" +
	"\x1aCheckContentChangeResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x1a\n" +
	"\brevision\x18\x03 \x01(\x04R\brevision\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\xdf\x01\n" +
	"\x13ListSubjectsRequest\x12\x14\n" +
	"\x05store\x18\x01 \x01(\tR\x05store\x12)\n" +
	"\x10object_namespace\x18\x02 \x01(\tR\x0fobjectNamespace\x12\x1b\n" +
	"\tobject_id\x18\x03 \x01(\tR\bobjectId\x12\x1a\n" +
	"\brelation\x18\x04 \x01(\tR\brelation\x128\n" +
	"\vconsistency\x18\x05 \x01(\v2\x16.zenith.v2.ConsistencyR\vconsistency\x12\x14\n" +
	"\x05limit\x18\x06 \x01(\rR\x05limit\"\x80\x01\n" +
	"\aSubject\x12+\n" +
	"\x11subject_namespace\x18\x01 \x01(\tR\x10subjectNamespace\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x02 \x01(\tR\tsubjectId\x12)\n" +
	"\x10subject_relation\x18\x03 \x01(\tR\x0fsubjectRelation\"\xaa\x01\n" +
	"\x14ListSubjectsResponse\x12.\n" +
	"\bsubjects\x18\x01 \x03(\v2\x12.zenith.v2.SubjectR\bsubjects\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x1a\n" +
	"\brevision\x18\x03 \x01(\x04R\brevision\x12\x1a\n" +
	"\bcomplete\x18\x04 \x01(\bR\bcomplete\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"e\n" +
	"\x18GetRequestOutcomeRequest\x12\x18\n" +
	"\asession\x18\x01 \x01(\tR\asession\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\"{\n" +
	"\x19GetRequestOutcomeResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\x04R\brevision\x12\x16\n" +
	"\x06result\x18\x03 \x01(\tR\x06result\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\x19\n" +
	"\x17GetClusterStatusRequest\"\x8a\x01\n" +
	"\x18GetClusterStatusResponse\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x04R\x04term\x12!\n" +
	"\fcommit_index\x18\x03 \x01(\x04R\vcommitIndex\x12#\n" +
	"\rapplied_index\x18\x04 \x01(\x04R\fappliedIndex\",\n" +
	"\x11AddLearnerRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x04R\x06nodeId\"-\n" +
	"\x13ProposeJointRequest\x12\x16\n" +
	"\x06voters\x18\x01 \x03(\x04R\x06voters\":\n" +
	"\x12MembershipResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok2\xbe\x06\n" +
	"\x06Zenith\x12:\n" +
	"\x05Check\x12\x17.zenith.v2.CheckRequest\x1a\x18.zenith.v2.CheckResponse\x12I\n" +
	"\n" +
	"BatchCheck\x12\x1c.zenith.v2.BatchCheckRequest\x1a\x1d.zenith.v2.BatchCheckResponse\x12L\n" +
	"\vWriteTuples\x12\x1d.zenith.v2.WriteTuplesRequest\x1a\x1e.zenith.v2.WriteTuplesResponse\x12a\n" +
	"\x12CheckContentChange\x12$.zenith.v2.CheckContentChangeRequest\x1a%.zenith.v2.CheckContentChangeResponse\x12O\n" +
	"\fListSubjects\x12\x1e.zenith.v2.ListSubjectsRequest\x1a\x1f.zenith.v2.ListSubjectsResponse\x12^\n" +
	"\x11GetRequestOutcome\x12#.zenith.v2.GetRequestOutcomeRequest\x1a$.zenith.v2.GetRequestOutcomeResponse\x12[\n" +
	"\x10GetClusterStatus\x12\".zenith.v2.GetClusterStatusRequest\x1a#.zenith.v2.GetClusterStatusResponse\x12I\n" +
	"\n" +
	"AddLearner\x12\x1c.zenith.v2.AddLearnerRequest\x1a\x1d.zenith.v2.MembershipResponse\x12M\n" +
	"\fProposeJoint\x12\x1e.zenith.v2.ProposeJointRequest\x1a\x1d.zenith.v2.MembershipResponse\x12T\n" +
	"\x0fProposeFinalize\x12\".zenith.v2.GetClusterStatusRequest\x1a\x1d.zenith.v2.MembershipResponseB1Z/github.com/yxshwanth/zenith/api/zenith/v2/pb;pbb\x06proto3"

var (
	file_zenith_proto_rawDescOnce sync.Once
	file_zenith_proto_rawDescData []byte
)

func file_zenith_proto_rawDescGZIP() []byte {
	file_zenith_proto_rawDescOnce.Do(func() {
		file_zenith_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zenith_proto_rawDesc), len(file_zenith_proto_rawDesc)))
	})
	return file_zenith_proto_rawDescData
}

var file_zenith_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_zenith_proto_goTypes = []any{
	(*Consistency)(nil),                // 0: zenith.v2.Consistency
	(*Tuple)(nil),                      // 1: zenith.v2.Tuple
	(*CheckRequest)(nil),               // 2: zenith.v2.CheckRequest
	(*CheckResponse)(nil),              // 3: zenith.v2.CheckResponse
	(*BatchCheckRequest)(nil),          // 4: zenith.v2.BatchCheckRequest
	(*BatchCheckResponse)(nil),         // 5: zenith.v2.BatchCheckResponse
	(*WriteTuplesRequest)(nil),         // 6: zenith.v2.WriteTuplesRequest
	(*WriteTuplesResponse)(nil),        // 7: zenith.v2.WriteTuplesResponse
	(*CheckContentChangeRequest)(nil),  // 8: zenith.v2.CheckContentChangeRequest
	(*CheckContentChangeResponse)(nil), // 9: zenith.v2.CheckContentChangeResponse
	(*ListSubjectsRequest)(nil),        // 10: zenith.v2.ListSubjectsRequest
	(*Subject)(nil),                    // 11: zenith.v2.Subject
	(*ListSubjectsResponse)(nil),       // 12: zenith.v2.ListSubjectsResponse
	(*GetRequestOutcomeRequest)(nil),   // 13: zenith.v2.GetRequestOutcomeRequest
	(*GetRequestOutcomeResponse)(nil),  // 14: zenith.v2.GetRequestOutcomeResponse
	(*GetClusterStatusRequest)(nil),    // 15: zenith.v2.GetClusterStatusRequest
	(*GetClusterStatusResponse)(nil),   // 16: zenith.v2.GetClusterStatusResponse
	(*AddLearnerRequest)(nil),          // 17: zenith.v2.AddLearnerRequest
	(*ProposeJointRequest)(nil),        // 18: zenith.v2.ProposeJointRequest
	(*MembershipResponse)(nil),         // 19: zenith.v2.MembershipResponse
}
var file_zenith_proto_depIdxs = []int32{
	0,  // 0: zenith.v2.CheckRequest.consistency:type_name -> zenith.v2.Consistency
	0,  // 1: zenith.v2.BatchCheckRequest.consistency:type_name -> zenith.v2.Consistency
	2,  // 2: zenith.v2.BatchCheckRequest.items:type_name -> zenith.v2.CheckRequest
	3,  // 3: zenith.v2.BatchCheckResponse.results:type_name -> zenith.v2.CheckResponse
	1,  // 4: zenith.v2.WriteTuplesRequest.tuples:type_name -> zenith.v2.Tuple
	1,  // 5: zenith.v2.WriteTuplesRequest.deletes:type_name -> zenith.v2.Tuple
	0,  // 6: zenith.v2.ListSubjectsRequest.consistency:type_name -> zenith.v2.Consistency
	11, // 7: zenith.v2.ListSubjectsResponse.subjects:type_name -> zenith.v2.Subject
	2,  // 8: zenith.v2.Zenith.Check:input_type -> zenith.v2.CheckRequest
	4,  // 9: zenith.v2.Zenith.BatchCheck:input_type -> zenith.v2.BatchCheckRequest
	6,  // 10: zenith.v2.Zenith.WriteTuples:input_type -> zenith.v2.WriteTuplesRequest
	8,  // 11: zenith.v2.Zenith.CheckContentChange:input_type -> zenith.v2.CheckContentChangeRequest
	10, // 12: zenith.v2.Zenith.ListSubjects:input_type -> zenith.v2.ListSubjectsRequest
	13, // 13: zenith.v2.Zenith.GetRequestOutcome:input_type -> zenith.v2.GetRequestOutcomeRequest
	15, // 14: zenith.v2.Zenith.GetClusterStatus:input_type -> zenith.v2.GetClusterStatusRequest
	17, // 15: zenith.v2.Zenith.AddLearner:input_type -> zenith.v2.AddLearnerRequest
	18, // 16: zenith.v2.Zenith.ProposeJoint:input_type -> zenith.v2.ProposeJointRequest
	15, // 17: zenith.v2.Zenith.ProposeFinalize:input_type -> zenith.v2.GetClusterStatusRequest
	3,  // 18: zenith.v2.Zenith.Check:output_type -> zenith.v2.CheckResponse
	5,  // 19: zenith.v2.Zenith.BatchCheck:output_type -> zenith.v2.BatchCheckResponse
	7,  // 20: zenith.v2.Zenith.WriteTuples:output_type -> zenith.v2.WriteTuplesResponse
	9,  // 21: zenith.v2.Zenith.CheckContentChange:output_type -> zenith.v2.CheckContentChangeResponse
	12, // 22: zenith.v2.Zenith.ListSubjects:output_type -> zenith.v2.ListSubjectsResponse
	14, // 23: zenith.v2.Zenith.GetRequestOutcome:output_type -> zenith.v2.GetRequestOutcomeResponse
	16, // 24: zenith.v2.Zenith.GetClusterStatus:output_type -> zenith.v2.GetClusterStatusResponse
	19, // 25: zenith.v2.Zenith.AddLearner:output_type -> zenith.v2.MembershipResponse
	19, // 26: zenith.v2.Zenith.ProposeJoint:output_type -> zenith.v2.MembershipResponse
	19, // 27: zenith.v2.Zenith.ProposeFinalize:output_type -> zenith.v2.MembershipResponse
	18, // [18:28] is the sub-list for method output_type
	8,  // [8:18] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_zenith_proto_init() }
func file_zenith_proto_init() {
	if File_zenith_proto != nil {
		return
	}
	file_zenith_proto_msgTypes[0].OneofWrappers = []any{
		(*Consistency_FullyConsistent)(nil),
		(*Consistency_AtLeastAsFresh)(nil),
		(*Consistency_AtExactRevision)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zenith_proto_rawDesc), len(file_zenith_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_zenith_proto_goTypes,
		DependencyIndexes: file_zenith_proto_depIdxs,
		MessageInfos:      file_zenith_proto_msgTypes,
	}.Build()
	File_zenith_proto = out.File
	file_zenith_proto_goTypes = nil
	file_zenith_proto_depIdxs = nil
}
